export type Vec3 = [number, number, number]

export type PrimitiveKind = 'box' | 'sphere' | 'cylinder' | 'cone' | 'torus'
export type ObjectKind = PrimitiveKind | 'model'

export type SceneObject = {
  id: string
  name: string
  kind: ObjectKind
  /** Original file name for kind === 'model' (e.g. "chair.glb") */
  fileName?: string
  color: string
  position: Vec3
  rotation: Vec3 // radians, XYZ euler (three.js convention)
  scale: Vec3
}

/**
 * Geometry args shared by the live viewport and the exported JSX so the
 * pasted code renders exactly what was arranged.
 */
export const GEOMETRY_ARGS = {
  box: [1, 1, 1],
  sphere: [0.5, 32, 32],
  cylinder: [0.5, 0.5, 1, 32],
  cone: [0.5, 1, 32],
  torus: [0.45, 0.16, 16, 48],
} as const

export const PRIMITIVE_KINDS: Array<PrimitiveKind> = [
  'box',
  'sphere',
  'cylinder',
  'cone',
  'torus',
]

/** Resting height so a freshly spawned primitive sits on the floor. */
export const SPAWN_HEIGHT: Record<PrimitiveKind, number> = {
  box: 0.5,
  sphere: 0.5,
  cylinder: 0.5,
  cone: 0.5,
  torus: 0.61,
}

export function fmt(n: number): string {
  const rounded = Math.round(n * 1000) / 1000
  // Avoid "-0"
  return String(rounded === 0 ? 0 : rounded)
}

function fmtVec(v: Vec3): string {
  return `[${v.map(fmt).join(', ')}]`
}

function isIdentity(v: Vec3, identity: number): boolean {
  return v.every((n) => Math.abs(n - identity) < 0.0005)
}

export function toSceneJson(objects: Array<SceneObject>): string {
  const round = (v: Vec3) => v.map((n) => Number(fmt(n))) as Vec3
  return JSON.stringify(
    {
      version: 1,
      units: { rotation: 'radians' },
      objects: objects.map((o) => ({
        name: o.name,
        kind: o.kind,
        ...(o.kind === 'model' ? { file: o.fileName } : { color: o.color }),
        position: round(o.position),
        rotation: round(o.rotation),
        scale: round(o.scale),
      })),
    },
    null,
    2,
  )
}

const GEOMETRY_JSX: Record<PrimitiveKind, string> = {
  box: `<boxGeometry args={[${GEOMETRY_ARGS.box.join(', ')}]} />`,
  sphere: `<sphereGeometry args={[${GEOMETRY_ARGS.sphere.join(', ')}]} />`,
  cylinder: `<cylinderGeometry args={[${GEOMETRY_ARGS.cylinder.join(', ')}]} />`,
  cone: `<coneGeometry args={[${GEOMETRY_ARGS.cone.join(', ')}]} />`,
  torus: `<torusGeometry args={[${GEOMETRY_ARGS.torus.join(', ')}]} />`,
}

function transformProps(o: SceneObject): string {
  let props = ` position={${fmtVec(o.position)}}`
  if (!isIdentity(o.rotation, 0)) props += ` rotation={${fmtVec(o.rotation)}}`
  if (!isIdentity(o.scale, 1)) props += ` scale={${fmtVec(o.scale)}}`
  return props
}

export function toJsx(objects: Array<SceneObject>): string {
  const hasModels = objects.some((o) => o.kind === 'model')
  const lines: Array<string> = [
    '// Generated by Setpiece. Rotations are radians (three.js XYZ euler).',
  ]
  if (hasModels) {
    lines.push(
      "// Models load from /public/models — copy your .glb files there.",
      "import { Gltf } from '@react-three/drei'",
    )
  }
  lines.push('', 'export function ArrangedScene() {', '  return (', '    <group>')

  for (const o of objects) {
    if (o.kind === 'model') {
      lines.push(
        `      {/* ${o.name} */}`,
        `      <Gltf src="/models/${o.fileName ?? 'model.glb'}"${transformProps(o)} />`,
      )
    } else {
      lines.push(
        `      {/* ${o.name} */}`,
        `      <mesh${transformProps(o)} castShadow receiveShadow>`,
        `        ${GEOMETRY_JSX[o.kind]}`,
        `        <meshStandardMaterial color="${o.color}" />`,
        `      </mesh>`,
      )
    }
  }

  lines.push('    </group>', '  )', '}', '')
  return lines.join('\n')
}
